# Generated by Django 6.0.3 on 2026-03-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('plataforma', models.CharField(max_length=200)),
                ('imagen', models.CharField(default='default.png', max_length=200)),
            ],
        ),
    ]
